version: "3"

services:
  corrections:
    depends_on:
      - "dynamodb-local"
    container_name: corrections_web
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "/init-dynamodb.sh && python -m pytest"
    volumes:
      - .:/code
    env_file:
      - .env.ci
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: corrections_dynamodb
    ports:
      - "8000:8000"
