version: "3"

services:
  corrections:
    depends_on:
      - "dynamodb-local"
      - "mysql-local"
    container_name: corrections_web
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "/init-dynamodb.sh && flask run --host=0.0.0.0"
    volumes:
      - .:/code
    ports:
      - "5500:5000"
    env_file:
      - .env.local
  mysql-local:
    image: mysql:5.7.22
    container_name: corrections_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    env_file:
      - .env.local
    ports:
      - "3406:3306"
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: corrections_dynamodb
    ports:
      - "8000:8000"
