version: '3'

services:
  corrections:
    container_name: corrections_web
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: uwsgi --ini uwsgi.ini
    ports:
      - "5002:5002"
    restart: on-failure
    env_file:
      - .env.local

